# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Review:
      type: "object"
      required:
        - artista
        - album
        - score
        - review
      properties:
        artista:
          type: "string"
        album:
          type: "string"
        score:
          type: "string"
        review:
          type: "string"

paths:
  /reviews:
    get:
      operationId: "review.read_all"
      tags:
        - "Reviews"
      summary: "Read reviews"
      responses:
        "200":
          description: "Successfully read reviews"
    post:
      operationId: "review.create"
      tags:
        - Review
      summary: "Create a review"
      requestBody:
        description: "Review to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "review"
              $ref: "#/components/schemas/Review"
      responses:
        "201":
          description: "Successfully created Review"